general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = niri msg action power-on-monitors
}

listener {
    timeout = 1800
    on-timeout = hyprlock
}

# Monitors off 2 minutes after lock (1800 + 120)
listener {
    timeout = 1920
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
